### PR TITLE
Generate a new forwarding secret file if the file is deleted

### LINKED ISSUE #1670: Velocity is not attempting to restore forwarding.secret
### Expected Behavior

If I delete the 
forwarding.secret file, Velocity should restore it and generate a new key.

### Actual Behavior

After deleting the file, Velocity simply crashes with an error. 

[14:33:26 ERROR]: Unable to read/load/save your velocity.toml. The server will shut down.
java.lang.RuntimeException: The forwarding-secret-file does not exist.
        at com.velocitypowered.proxy.config.VelocityConfiguration.read(VelocityConfiguration.java:531) ~[velocity-3.4.0-SNAPSHOT-551.jar:3.4.0-SNAPSHOT (git-67b988e6-b551)]
        at com.velocitypowered.proxy.VelocityServer.doStartupConfigLoad(VelocityServer.java:405) ~[velocity-3.4.0-SNAPSHOT-551.jar:3.4.0-SNAPSHOT (git-67b988e6-b551)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:293) ~[velocity-3.4.0-SNAPSHOT-551.jar:3.4.0-SNAPSHOT (git-67b988e6-b551)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-3.4.0-SNAPSHOT-551.jar:3.4.0-SNAPSHOT (git-67b988e6-b551)]

### Steps to Reproduce

1. Download the latest version of Velocity

2. Run it.

3. Stop the proxy and delete 
forwarding.secret 

4. Run it and you will see that Velocity did not try to generate a new one.

### Plugin List

> velocity plugins
[14:39:16 INFO]: Плагины: velocity

### Velocity Version

> velocity info
[14:39:24 INFO]: Velocity 3.4.0-SNAPSHOT (git-67b988e6-b551)
[14:39:24 INFO]: Copyright 2018-2025 Velocity Contributors. Velocity лицензирована на условиях GNU General Public License v3.
[14:39:24 INFO]: PaperMC - GitHub

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by 4drian3d**
This allows to generate a new forwarding secret simply by deleting the file if required. The file will only be generated if the forwarding secret is not configured through a system property

resolves #1670

### CODE REVIEW

**Review by R00tB33rMan — APPROVED** [review]

**Review by jonesdevelopment — APPROVED** [review]

File: proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java [hunk 1]
```diff
@@ -528,7 +528,9 @@ public static VelocityConfiguration read(Path path) throws IOException {
                     "The file " + forwardSecretFile + " is not a valid file or it is a directory.");
           }
         } else {
-          throw new RuntimeException("The forwarding-secret-file does not exist.");
```
Comment (electronicboy) [inline proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java:531]: I would probably print something at the very least, just for the sake of debugging certain types of setups
