### PR TITLE
Fix HoverEvent.showEntity() in protocol versions prior to 1.21.5

### LINKED ISSUE #1577: Client unexpectedly disconnect due to Component with HoverEvent.showEntity
### Expected Behavior

1. Create a Component with a `HoverEvent.showEntity()`.
2. send it to a player connected to the proxy by `player.sendMessage()`.
3. The client of the player show the component in the chat correctly with the hover event.

### Actual Behavior

Immediately after the message is sent. The client unexpectedly disconnected with a reason of internal exception occurred: `JsonSyntaxException: Missing type, expected to find a string`

### Steps to Reproduce

```
Optional<Player> optional = proxyServer.getPlayer(...);
Component message = Component.text(...).hoverEvent(HoverEvent.showEntity(...));
optional.ifPresent(player -> player.sendMessage(message));
```

### Plugin List

Only my plugin on the velocity and no plugins on the backend server.

### Velocity Version

```
> velocity info
[22:50:17 INFO]: Velocity 3.4.0-SNAPSHOT (git-5eb83760-b506)
[22:50:17 INFO]: Copyright 2018-2023 Velocity Contributors。Velocity 以 GNU 通用公共许可证第三版授权。
[22:50:17 INFO]: PaperMC - GitHub
```

### Additional Information

The **client** minecraft version is `1.20.1`. Possible reason of this bug may be the PR #1564 that introduces support for new hover event schema in 1.21.5 controlled by `JSONOptions.EMIT_HOVER_SHOW_ENTITY_KEY_AS_TYPE_AND_UUID_AS_ID`. This option is **FALSE** by default which means it has to be explicitly set to true in the `OptionSchema`. However in the `com.velocitypowered.proxy.protocol.ProtocolUtils` only `MODERN_SERIALIZER` _set that option to false explicitly_ , leaving all other serializers use the default value false, which may cause all versions prior to 1.21.5 to encounter same problem because the `type` key is missing.

### PR DESCRIPTION
**Pull request by Argon4W**
This PR fixes #1577

### CODE REVIEW

File: proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java [hunk 1]
```diff
@@ -97,6 +98,7 @@ public enum ProtocolUtils {
               .value(JSONOptions.EMIT_RGB, Boolean.TRUE)
               .value(JSONOptions.EMIT_HOVER_EVENT_TYPE, JSONOptions.HoverEventValueMode.CAMEL_CASE)
               .value(JSONOptions.EMIT_CLICK_EVENT_TYPE, JSONOptions.ClickEventValueMode.CAMEL_CASE)
+              .value(JSONOptions.EMIT_HOVER_SHOW_ENTITY_KEY_AS_TYPE_AND_UUID_AS_ID, true)
```
Comment (electronicboy) [inline proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java:101]: I believe that both of these should belong in the "after 1.20.3" section for documentation reasons, at least, that's where it was in the past

**Review by electronicboy — CHANGES_REQUESTED** [review]

File: proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java (hunk 1 above)
Comment (Argon4W) [reply proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java:101]: What do you mean by "both", the JSONOptions.EMIT_HOVER_SHOW_ENTITY_KEY_AS_TYPE_AND_UUID_AS_ID in the PRE_1_20_3_SERIALIZER and PRE_1_21_5_SERIALIZER should belong to "after 1.20.3"? But PRE_1_20_3 means prior to 1.20.3, I think. And "show_entity" indeed uses "type" and "id" after 1.16 instead of after 1.20.3

**Review by electronicboy — APPROVED** [review]
